/*
 * CastlingJFrame.java
 *
 * Created on 16/10/2009, 15:12:09
 */

package view;

import java.awt.Rectangle;
import xadrezonator.Game;
import xadrezonator.Player;

/**
 *
 * @author Bernardo Botelho
 */
public class CastlingJFrame extends javax.swing.JDialog implements InterfaceConstants {

    private Game game;
    private Player player;
    private int chosenCastling;

    public CastlingJFrame(){}

    /** Creates new form CastlingJFrame */
    public CastlingJFrame(Game gameParam, Player playerParam, Rectangle r) {
        initComponents();
        this.game = gameParam;
        this.player = playerParam;
        if (this.game.availLongCastling(this.player))
            buttonLong.setEnabled(true);
        else
            buttonLong.setEnabled(false);
        if (this.game.availShortCastling(this.player))
            buttonShort.setEnabled(true);
        else
            buttonShort.setEnabled(false);
        
        setBounds((int)((r.getX() + r.getWidth()) - getWidth()) / 2,
                ((int)(r.getY() + r.getHeight()) - getHeight()) / 3,
                getWidth(), getHeight());
    }

    public int getChosenCastling() {
        return chosenCastling;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonShort = new javax.swing.JButton();
        buttonLong = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Castling");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);

        jLabel1.setText("Qual tipo de roque você deseja executar?");

        buttonShort.setText("Roque Pequeno");
        buttonShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShortActionPerformed(evt);
            }
        });

        buttonLong.setText("Roque Grande");
        buttonLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLongActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonShort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonLong, buttonShort, cancelButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonShort)
                    .addComponent(cancelButton)
                    .addComponent(buttonLong))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        chosenCastling = -1;
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void buttonShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShortActionPerformed
        chosenCastling = SHORT_CASTLING;
        this.dispose();
    }//GEN-LAST:event_buttonShortActionPerformed

    private void buttonLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLongActionPerformed
        chosenCastling = LONG_CASTLING;
        this.dispose();
    }//GEN-LAST:event_buttonLongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLong;
    private javax.swing.JButton buttonShort;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
