package view;

import java.awt.Rectangle;

public class PromotionJFrame extends javax.swing.JDialog
        implements InterfaceConstants {

    /** Creates new form PromotionJFrame */
    public PromotionJFrame(Rectangle r) {
        initComponents();
        setSelectedPiece(0);

        setBounds((int)((r.getX() + r.getWidth()) - getWidth()) / 2,
                ((int)(r.getY() + r.getHeight()) - getHeight()) / 3,
                getWidth(), getHeight());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBishop = new javax.swing.JButton();
        jButtonHorse = new javax.swing.JButton();
        jButtonQueen = new javax.swing.JButton();
        jButtonRook = new javax.swing.JButton();
        jButtonPromote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Promoção do Peão");
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha a peça"));

        jButtonBishop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/white/bishop.png"))); // NOI18N
        jButtonBishop.setToolTipText("Bishop");
        jButtonBishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBishopActionPerformed(evt);
            }
        });

        jButtonHorse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/white/horse.png"))); // NOI18N
        jButtonHorse.setToolTipText("Horse");
        jButtonHorse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHorseActionPerformed(evt);
            }
        });

        jButtonQueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/white/queen.png"))); // NOI18N
        jButtonQueen.setToolTipText("Queen");
        jButtonQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueenActionPerformed(evt);
            }
        });

        jButtonRook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/white/rook.png"))); // NOI18N
        jButtonRook.setToolTipText("Rook");
        jButtonRook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBishop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHorse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQueen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonQueen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jButtonRook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jButtonHorse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jButtonBishop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonPromote.setText("Promover");
        jButtonPromote.setEnabled(false);
        jButtonPromote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButtonPromote, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPromote, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBishopActionPerformed
        jButtonBishop.setEnabled(false);
        jButtonHorse.setEnabled(true);
        jButtonQueen.setEnabled(true);
        jButtonRook.setEnabled(true);

        setSelectedPiece(BISHOP);

        jButtonPromote.setEnabled(true);
    }//GEN-LAST:event_jButtonBishopActionPerformed

    private void jButtonHorseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHorseActionPerformed
        jButtonBishop.setEnabled(true);
        jButtonHorse.setEnabled(false);
        jButtonQueen.setEnabled(true);
        jButtonRook.setEnabled(true);

        setSelectedPiece(HORSE);

        jButtonPromote.setEnabled(true);
    }//GEN-LAST:event_jButtonHorseActionPerformed

    private void jButtonQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueenActionPerformed
        jButtonBishop.setEnabled(true);
        jButtonHorse.setEnabled(true);
        jButtonQueen.setEnabled(false);
        jButtonRook.setEnabled(true);


        setSelectedPiece(QUEEN);

        jButtonPromote.setEnabled(true);
    }//GEN-LAST:event_jButtonQueenActionPerformed

    private void jButtonRookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRookActionPerformed
        jButtonBishop.setEnabled(true);
        jButtonHorse.setEnabled(true);
        jButtonQueen.setEnabled(true);
        jButtonRook.setEnabled(false);

        setSelectedPiece(ROOK);

        jButtonPromote.setEnabled(true);
    }//GEN-LAST:event_jButtonRookActionPerformed

    private void jButtonPromoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromoteActionPerformed
        //Fecha a janela
        this.dispose();
    }//GEN-LAST:event_jButtonPromoteActionPerformed

    public int getSelectedPiece() {
        return selectedPiece;
    }

    public void setSelectedPiece(int selectedPiece) {
        this.selectedPiece = selectedPiece;
    }

    private int selectedPiece;//Constantes em InterfaceConstants
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBishop;
    private javax.swing.JButton jButtonHorse;
    private javax.swing.JButton jButtonPromote;
    private javax.swing.JButton jButtonQueen;
    private javax.swing.JButton jButtonRook;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
